// Copyright 2024
// Golden-fixture compatibility lock for the Snapshot serialization formats.
//
// The fixtures tests/data/golden_snapshot_v2.bin and .json were generated by
// the PRE-refactor serializers (run this binary with --generate, exactly
// once, and commit the outputs). The tests assert that:
//   1. The fixtures load (deserialize) without error.
//   2. Re-serializing the loaded snapshot is byte/string-IDENTICAL to the
//      fixture. Any change to the wire format breaks these tests.
//   3. Serializing a freshly built maximally-populated snapshot reproduces
//      the fixtures exactly (locks the builder <-> format mapping).
//
// If the fixtures are missing the tests FAIL LOUDLY. They are never
// regenerated silently: regeneration is only valid for a deliberate,
// versioned format change (bump the binary/JSON version first).

#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "../src/core/annotations.h"
#include "../src/core/cell.h"
#include "../src/core/object.h"
#include "../src/core/snapshot.h"
#include "../src/core/snapshot_json.h"
#include "../src/core/types.h"

using namespace companions;

#ifndef TESTS_DATA_DIR
#error "TESTS_DATA_DIR must be defined (see CMakeLists.txt)"
#endif

// =============================================================================
// Test macros
// =============================================================================
#define TEST(name) \
  void name(); \
  struct name##_registrar { \
    name##_registrar() { tests.push_back({#name, name}); } \
  } name##_instance; \
  void name()

#define ASSERT_TRUE(cond) \
  if (!(cond)) { \
    std::ostringstream oss; \
    oss << "ASSERT_TRUE failed: " << #cond << " at " << __FILE__ << ":" << __LINE__; \
    throw std::runtime_error(oss.str()); \
  }

#define ASSERT_EQ(a, b) \
  if ((a) != (b)) { \
    std::ostringstream oss; \
    oss << "ASSERT_EQ failed: " << #a << " != " << #b << " at " << __FILE__ << ":" << __LINE__; \
    throw std::runtime_error(oss.str()); \
  }

struct TestEntry {
  std::string name;
  void (*func)();
};
std::vector<TestEntry> tests;

// =============================================================================
// Fixture paths and I/O
// =============================================================================

const std::string kBinFixture = std::string(TESTS_DATA_DIR) + "/golden_snapshot_v2.bin";
const std::string kJsonFixture = std::string(TESTS_DATA_DIR) + "/golden_snapshot_v2.json";

std::vector<uint8_t> ReadBinaryFile(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  if (!f.is_open()) {
    throw std::runtime_error(
        "GOLDEN FIXTURE MISSING: " + path +
        "\nFixtures are the serialization-compatibility lock. They must be "
        "committed, never regenerated silently. If this is a deliberate "
        "format change, bump the snapshot version and regenerate with "
        "--generate.");
  }
  return std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),
                              std::istreambuf_iterator<char>());
}

std::string ReadTextFile(const std::string& path) {
  std::ifstream f(path, std::ios::binary);  // binary: no newline translation
  if (!f.is_open()) {
    throw std::runtime_error(
        "GOLDEN FIXTURE MISSING: " + path +
        "\nFixtures are the serialization-compatibility lock. They must be "
        "committed, never regenerated silently. If this is a deliberate "
        "format change, bump the snapshot version and regenerate with "
        "--generate.");
  }
  return std::string((std::istreambuf_iterator<char>(f)),
                     std::istreambuf_iterator<char>());
}

// =============================================================================
// Maximally-populated snapshot builder (deterministic, no RNG, no env)
// =============================================================================
// Exercises every field of every snapshot struct with non-default values:
// all CellKind/CellOrigin values, an agent without FSM, an FSM enemy
// mid-attack with statuses + cadence + patrol path, a dead agent, two
// effects (telegraph and active, with target_actors), top-level patrol
// path, cell- and agent-target annotations with params, and non-default
// tick/horizon/rng/d4.
Snapshot BuildGoldenSnapshot() {
  Snapshot s;
  s.rows = 4;
  s.cols = 5;
  s.cells.resize(20);
  for (int i = 0; i < 20; ++i) {
    s.cells[i].kind = static_cast<CellKind>(i % 4);          // Floor..HealArea
    s.cells[i].origin = static_cast<CellOrigin>((i / 5) % 4); // Default..Obstacle
  }

  // Agent 0: player, no FSM, two statuses.
  AgentSnapshot player;
  player.id = 1;
  player.type = static_cast<int>(ObjectType::Player);
  player.position = {1, 2};
  player.prev_position = {1, 1};
  player.health = 2;
  player.max_health = 5;
  player.agent_index = 0;
  player.faction = static_cast<int>(Faction::COMPANION);
  player.direction = static_cast<int>(Direction::Right);
  player.color = static_cast<int>(ActorColor::Red);
  player.alive = true;
  player.statuses.push_back(StatusSnapshot{static_cast<int>(StatusType::Stunned), 3});
  player.statuses.push_back(StatusSnapshot{static_cast<int>(StatusType::Marked), 7});
  player.has_fsm = false;
  player.cadence = {};
  player.tick = 13;
  s.agents.push_back(player);

  // Agent 1: FSM enemy mid-attack.
  AgentSnapshot enemy;
  enemy.id = 2;
  enemy.type = static_cast<int>(ObjectType::AgentFSM);
  enemy.position = {3, 4};
  enemy.prev_position = {3, 3};
  enemy.health = 4;
  enemy.max_health = 6;
  enemy.agent_index = -1;
  enemy.faction = static_cast<int>(Faction::ENEMY);
  enemy.direction = static_cast<int>(Direction::Down);
  enemy.color = static_cast<int>(ActorColor::Green);
  enemy.alive = true;
  enemy.statuses.push_back(StatusSnapshot{static_cast<int>(StatusType::Slowed), 2});
  enemy.has_fsm = true;
  enemy.fsm.state_type = FSMStateType::Attack;
  enemy.fsm.target_id = 1;
  enemy.fsm.patrol_path = {{2, 1}, {2, 3}, {3, 3}};
  enemy.fsm.patrol_index = 2;
  enemy.fsm.patrol_forward = false;
  enemy.fsm.detection_range = 7;
  enemy.fsm.lose_target_range = 9;
  enemy.fsm.rng_state = 0xA1B2C3D4E5F60718ULL;
  enemy.fsm.rng_inc = 0x1122334455667789ULL;
  enemy.fsm.attack_tick_counter = 2;
  enemy.fsm.attack_target_position = {1, 2};
  enemy.fsm.attack_area_width = 3;
  enemy.fsm.attack_area_height = 2;
  enemy.fsm.attack_damage = 2;
  enemy.fsm.attack_filter = TargetFilter::Companion;
  enemy.cadence = {1, 0, 1};
  enemy.tick = 42;
  s.agents.push_back(enemy);

  // Agent 2: dead companion (covers alive == false).
  AgentSnapshot dead;
  dead.id = 3;
  dead.type = static_cast<int>(ObjectType::Companion);
  dead.position = {0, 0};
  dead.prev_position = {0, 1};
  dead.health = 0;
  dead.max_health = 3;
  dead.agent_index = 1;
  dead.faction = static_cast<int>(Faction::COMPANION);
  dead.direction = static_cast<int>(Direction::Left);
  dead.color = static_cast<int>(ActorColor::Blue);
  dead.alive = false;
  dead.has_fsm = false;
  dead.cadence = {2};
  dead.tick = 5;
  s.agents.push_back(dead);

  // Effects: one in telegraph, one active with target_actors.
  EffectSnapshot e1;
  e1.effect_name = "fire_burst";
  e1.target_type = 0;
  e1.target_cell = {2, 2};
  e1.target_actor_id = -1;
  e1.target_actors = {};
  e1.direction = static_cast<int>(Direction::Up);
  e1.ticks_remaining = 3;
  e1.in_telegraph = true;
  e1.loops_remaining = 1;
  e1.source_id = 2;
  s.effects.push_back(e1);

  EffectSnapshot e2;
  e2.effect_name = "poison_cloud";
  e2.target_type = 1;
  e2.target_cell = {0, 3};
  e2.target_actor_id = 1;
  e2.target_actors = {1, 3};
  e2.direction = static_cast<int>(Direction::Right);
  e2.ticks_remaining = 1;
  e2.in_telegraph = false;
  e2.loops_remaining = 0;
  e2.source_id = -1;
  s.effects.push_back(e2);

  // Timing / RNG / D4.
  s.tick = 77;
  s.horizon = 250;
  s.rng_state = 0x123456789ABCDEF0ULL;
  s.rng_inc = 0x0FEDCBA987654321ULL;
  s.d4_transform = 5;

  // Top-level patrol path (AggroEnv-style).
  s.patrol_path = {{1, 1}, {1, 3}, {3, 3}, {3, 1}};

  // Annotations: cell-target with multi params, agent-target, lens-owned.
  AnnotationSnapshot a1;
  a1.target_type = 0;
  a1.pos = {2, 4};
  a1.agent_id = kInvalidObjectId;
  a1.tag = SemanticTag::SynchroGoal;
  a1.params = {{"alpha", "1"}, {"beta", "two"}};
  a1.owner_lens_id = -1;
  s.annotations.push_back(a1);

  AnnotationSnapshot a2;
  a2.target_type = 1;
  a2.pos = {-1, -1};
  a2.agent_id = 2;
  a2.tag = SemanticTag::HtnName;
  a2.params = {{"name", "warden"}};
  a2.owner_lens_id = -1;
  s.annotations.push_back(a2);

  AnnotationSnapshot a3;
  a3.target_type = 0;
  a3.pos = {0, 2};
  a3.agent_id = kInvalidObjectId;
  a3.tag = SemanticTag::AggroTarget;
  a3.params = {};
  a3.owner_lens_id = 7;
  s.annotations.push_back(a3);

  return s;
}

// =============================================================================
// Tests
// =============================================================================

TEST(TestGoldenBinaryFixtureRoundTrip) {
  std::vector<uint8_t> golden = ReadBinaryFile(kBinFixture);
  ASSERT_TRUE(!golden.empty());

  Snapshot snap = Snapshot::Deserialize(golden);
  std::vector<uint8_t> reserialized = snap.Serialize();

  ASSERT_EQ(reserialized.size(), golden.size());
  for (size_t i = 0; i < golden.size(); ++i) {
    if (reserialized[i] != golden[i]) {
      std::ostringstream oss;
      oss << "Binary golden mismatch at byte offset " << i << " (golden=0x"
          << std::hex << static_cast<int>(golden[i]) << ", got=0x"
          << static_cast<int>(reserialized[i]) << ")";
      throw std::runtime_error(oss.str());
    }
  }
}

TEST(TestGoldenBinaryMatchesBuilder) {
  std::vector<uint8_t> golden = ReadBinaryFile(kBinFixture);
  std::vector<uint8_t> built = BuildGoldenSnapshot().Serialize();

  ASSERT_EQ(built.size(), golden.size());
  for (size_t i = 0; i < golden.size(); ++i) {
    if (built[i] != golden[i]) {
      std::ostringstream oss;
      oss << "Serializing BuildGoldenSnapshot() diverges from the golden "
             "fixture at byte offset " << i;
      throw std::runtime_error(oss.str());
    }
  }
}

TEST(TestGoldenJsonFixtureRoundTrip) {
  std::string golden = ReadTextFile(kJsonFixture);
  ASSERT_TRUE(!golden.empty());

  Snapshot snap = SnapshotFromJson(golden);
  std::string reserialized = SnapshotToJson(snap);

  if (reserialized != golden) {
    size_t i = 0;
    while (i < golden.size() && i < reserialized.size() &&
           golden[i] == reserialized[i]) {
      ++i;
    }
    std::ostringstream oss;
    oss << "JSON golden mismatch at char offset " << i << ". Context: \""
        << golden.substr(i > 40 ? i - 40 : 0, 80) << "\" vs \""
        << reserialized.substr(i > 40 ? i - 40 : 0, 80) << "\"";
    throw std::runtime_error(oss.str());
  }
}

TEST(TestGoldenJsonMatchesBuilder) {
  std::string golden = ReadTextFile(kJsonFixture);
  std::string built = SnapshotToJson(BuildGoldenSnapshot());
  ASSERT_TRUE(built == golden);
}

// Cross-format: the binary fixture, converted to JSON, must reproduce the
// JSON fixture exactly. Locks the two formats to the same logical snapshot.
TEST(TestGoldenCrossFormat) {
  std::vector<uint8_t> golden_bin = ReadBinaryFile(kBinFixture);
  std::string golden_json = ReadTextFile(kJsonFixture);

  Snapshot snap = Snapshot::Deserialize(golden_bin);
  std::string as_json = SnapshotToJson(snap);
  ASSERT_TRUE(as_json == golden_json);

  // And back: JSON fixture -> binary must equal the binary fixture.
  Snapshot from_json = SnapshotFromJson(golden_json);
  std::vector<uint8_t> as_bin = from_json.Serialize();
  ASSERT_EQ(as_bin.size(), golden_bin.size());
  for (size_t i = 0; i < golden_bin.size(); ++i) {
    ASSERT_EQ(as_bin[i], golden_bin[i]);
  }
}

// =============================================================================
// Main (--generate writes the fixtures; only for deliberate format changes)
// =============================================================================

int main(int argc, char** argv) {
  if (argc > 1 && std::string(argv[1]) == "--generate") {
    Snapshot golden = BuildGoldenSnapshot();

    std::vector<uint8_t> bin = golden.Serialize();
    std::ofstream bf(kBinFixture, std::ios::binary);
    if (!bf.is_open()) {
      std::cerr << "Cannot write " << kBinFixture << "\n";
      return 1;
    }
    bf.write(reinterpret_cast<const char*>(bin.data()),
             static_cast<std::streamsize>(bin.size()));
    bf.close();

    std::string js = SnapshotToJson(golden);
    std::ofstream jf(kJsonFixture, std::ios::binary);
    if (!jf.is_open()) {
      std::cerr << "Cannot write " << kJsonFixture << "\n";
      return 1;
    }
    jf << js;
    jf.close();

    std::cout << "Wrote " << kBinFixture << " (" << bin.size() << " bytes)\n";
    std::cout << "Wrote " << kJsonFixture << " (" << js.size() << " chars)\n";
    return 0;
  }

  std::cout << "Running " << tests.size() << " golden snapshot tests...\n\n";

  int passed = 0;
  int failed = 0;
  for (const auto& test : tests) {
    std::cout << "  " << test.name << "... ";
    try {
      test.func();
      std::cout << "PASSED\n";
      passed++;
    } catch (const std::exception& e) {
      std::cout << "FAILED\n    " << e.what() << "\n";
      failed++;
    }
  }

  std::cout << "\nResults: " << passed << " passed, " << failed << " failed\n";
  return failed > 0 ? 1 : 0;
}
