// Copyright 2024
// Test suite for the C API

#include <cstring>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "companions_api.h"
#include "companions_version.hpp"  // generated by CMake into the build tree

// =============================================================================
// Test macros
// =============================================================================
#define TEST(name) \
  void name(); \
  struct name##_registrar { \
    name##_registrar() { tests.push_back({#name, name}); } \
  } name##_instance; \
  void name()

#define ASSERT_TRUE(cond) \
  if (!(cond)) { \
    std::ostringstream oss; \
    oss << "ASSERT_TRUE failed: " << #cond << " at " << __FILE__ << ":" << __LINE__; \
    throw std::runtime_error(oss.str()); \
  }

#define ASSERT_FALSE(cond) \
  if (cond) { \
    std::ostringstream oss; \
    oss << "ASSERT_FALSE failed: " << #cond << " at " << __FILE__ << ":" << __LINE__; \
    throw std::runtime_error(oss.str()); \
  }

#define ASSERT_EQ(a, b) \
  if ((a) != (b)) { \
    std::ostringstream oss; \
    oss << "ASSERT_EQ failed: " << (a) << " != " << (b) << " (" << #a << " != " << #b << ") at " << __FILE__ << ":" << __LINE__; \
    throw std::runtime_error(oss.str()); \
  }

#define ASSERT_NE(a, b) \
  if ((a) == (b)) { \
    std::ostringstream oss; \
    oss << "ASSERT_NE failed: " << #a << " == " << #b << " at " << __FILE__ << ":" << __LINE__; \
    throw std::runtime_error(oss.str()); \
  }

#define ASSERT_NOT_NULL(ptr) \
  if ((ptr) == nullptr) { \
    std::ostringstream oss; \
    oss << "ASSERT_NOT_NULL failed: " << #ptr << " is null at " << __FILE__ << ":" << __LINE__; \
    throw std::runtime_error(oss.str()); \
  }

struct TestEntry {
  std::string name;
  void (*func)();
};
std::vector<TestEntry> tests;

// =============================================================================
// Helper: Create default config
// =============================================================================
static Companions_EnvConfig MakeConfig(int rows = 12, int cols = 12, int companions = 3,
                               int synchro = 3, uint32_t seed = 42) {
  Companions_EnvConfig config = {};
  config.rows = rows;
  config.cols = cols;
  config.num_companions = companions;
  config.num_synchro = synchro;
  config.map_complexity = 0;
  config.horizon = 100;
  config.d4_transform = 0;
  config.seed = seed;
  return config;
}

// =============================================================================
// Lifecycle Tests
// =============================================================================
TEST(TestVersion) {
  const char* version = companions_version();
  ASSERT_NOT_NULL(version);
  ASSERT_TRUE(std::strlen(version) > 0);
  // The DLL must report the CMake project version (COMPANIONS_LIB_VERSION
  // from the generated companions_version.hpp), not a hardcoded string.
  ASSERT_TRUE(std::strcmp(version, COMPANIONS_LIB_VERSION) == 0);
  ASSERT_TRUE(std::strcmp(version, "1.0.0") != 0);
  std::cout << "  Version: " << version << std::endl;
}

TEST(TestCreateDestroy) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  ASSERT_NOT_NULL(env);

  ASSERT_EQ(companions_get_rows(env), 12);
  ASSERT_EQ(companions_get_cols(env), 12);
  ASSERT_EQ(companions_get_agent_count(env), 3);

  companions_destroy(env);
}

TEST(TestCreateWithNullConfig) {
  Companions_Env* env = companions_create(nullptr);
  ASSERT_TRUE(env == nullptr);
  const char* error = companions_get_error();
  ASSERT_NOT_NULL(error);
  ASSERT_TRUE(std::strlen(error) > 0);
}

// =============================================================================
// Reset Tests
// =============================================================================
TEST(TestReset) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  ASSERT_NOT_NULL(env);

  companions_reset(env, 42);
  ASSERT_EQ(companions_get_tick(env), 0);
  ASSERT_FALSE(companions_is_done(env));

  companions_destroy(env);
}

TEST(TestResetDeterminism) {
  Companions_EnvConfig config = MakeConfig();

  // Create two environments
  Companions_Env* env1 = companions_create(&config);
  Companions_Env* env2 = companions_create(&config);
  ASSERT_NOT_NULL(env1);
  ASSERT_NOT_NULL(env2);

  // Reset both with same seed
  companions_reset(env1, 123);
  companions_reset(env2, 123);

  // Get states
  Companions_GameState state1 = {};
  Companions_GameState state2 = {};
  companions_get_state(env1, &state1);
  companions_get_state(env2, &state2);

  // Should have same agent positions
  ASSERT_EQ(state1.agent_count, state2.agent_count);
  for (int i = 0; i < state1.agent_count; i++) {
    ASSERT_EQ(state1.agents[i].position.row, state2.agents[i].position.row);
    ASSERT_EQ(state1.agents[i].position.col, state2.agents[i].position.col);
  }

  companions_destroy(env1);
  companions_destroy(env2);
}

// =============================================================================
// State Query Tests
// =============================================================================
TEST(TestGetState) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  Companions_GameState state = {};
  companions_get_state(env, &state);

  ASSERT_EQ(state.rows, 12);
  ASSERT_EQ(state.cols, 12);
  ASSERT_EQ(state.agent_count, 3);
  ASSERT_FALSE(state.done);

  // All agents should be alive
  for (int i = 0; i < state.agent_count; i++) {
    ASSERT_TRUE(state.agents[i].alive);
    ASSERT_TRUE(state.agents[i].health > 0);
    ASSERT_TRUE(state.agents[i].position.row >= 0);
    ASSERT_TRUE(state.agents[i].position.col >= 0);
  }

  companions_destroy(env);
}

TEST(TestGetAgentByIndex) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  Companions_AgentState agent = {};
  bool found = companions_get_agent_by_index(env, 0, &agent);
  ASSERT_TRUE(found);
  ASSERT_TRUE(agent.alive);
  ASSERT_EQ(agent.agent_index, 0);

  // Out of range
  found = companions_get_agent_by_index(env, 99, &agent);
  ASSERT_FALSE(found);

  companions_destroy(env);
}

TEST(TestGetCell) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  // Corners should be walls (perimeter)
  ASSERT_EQ(companions_get_cell(env, 0, 0), Companions_CellKind_Wall);
  ASSERT_EQ(companions_get_cell(env, 0, 11), Companions_CellKind_Wall);
  ASSERT_EQ(companions_get_cell(env, 11, 0), Companions_CellKind_Wall);
  ASSERT_EQ(companions_get_cell(env, 11, 11), Companions_CellKind_Wall);

  // Interior cells are now all Floor (task-semantic role "synchro goal"
  // lives on the annotation layer, not on CellKind). Just verify the grid
  // comes back with only physical cell kinds.
  for (int r = 1; r < 11; r++) {
    for (int c = 1; c < 11; c++) {
      Companions_CellKind k = companions_get_cell(env, r, c);
      ASSERT_TRUE(k == Companions_CellKind_Floor || k == Companions_CellKind_Wall);
    }
  }

  companions_destroy(env);
}

TEST(TestGetGrid) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  std::vector<Companions_CellKind> grid(12 * 12);
  companions_get_grid(env, grid.data());

  // Top-left corner should be wall
  ASSERT_EQ(grid[0], Companions_CellKind_Wall);

  // Count walls (should be perimeter)
  int wall_count = 0;
  for (auto cell : grid) {
    if (cell == Companions_CellKind_Wall) wall_count++;
  }
  // Perimeter = 4*12 - 4 = 44 walls
  ASSERT_EQ(wall_count, 44);

  companions_destroy(env);
}

// =============================================================================
// Step Tests
// =============================================================================
TEST(TestStep) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  // All agents stay
  Companions_Action actions[3] = {
    {Companions_Movement_Stay, Companions_Interact_None},
    {Companions_Movement_Stay, Companions_Interact_None},
    {Companions_Movement_Stay, Companions_Interact_None}
  };

  Companions_StepResult result = {};
  companions_step(env, actions, 3, &result);

  ASSERT_EQ(companions_get_tick(env), 1);
  ASSERT_EQ(result.state.tick, 1);

  companions_destroy(env);
}

TEST(TestStepWithMovement) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  // Get initial position of first agent
  Companions_AgentState initial = {};
  companions_get_agent_by_index(env, 0, &initial);

  // Try to move first agent up (might be blocked by wall)
  Companions_Action actions[3] = {
    {Companions_Movement_Up, Companions_Interact_None},
    {Companions_Movement_Stay, Companions_Interact_None},
    {Companions_Movement_Stay, Companions_Interact_None}
  };

  Companions_StepResult result = {};
  companions_step(env, actions, 3, &result);

  // Should have generated some events
  // At minimum: movement or blocked event for agent 0
  ASSERT_TRUE(result.event_count >= 0);

  // Check the event types
  for (int i = 0; i < result.event_count; i++) {
    ASSERT_TRUE(result.events[i].type != Companions_Event_None);
  }

  companions_destroy(env);
}

TEST(TestStepGeneratesMovementEvents) {
  Companions_EnvConfig config = MakeConfig(6, 6, 1, 1, 42);  // Small grid, 1 agent
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  // Run multiple steps to find one where movement succeeds
  Companions_Action actions[1] = {{Companions_Movement_Down, Companions_Interact_None}};
  Companions_StepResult result = {};

  int move_events = 0;
  int blocked_events = 0;

  for (int step = 0; step < 10; step++) {
    companions_step(env, actions, 1, &result);

    for (int i = 0; i < result.event_count; i++) {
      if (result.events[i].type == Companions_Event_AgentMoved) {
        move_events++;
      } else if (result.events[i].type == Companions_Event_AgentBlocked) {
        blocked_events++;
      }
    }

    // Alternate directions
    actions[0].movement = static_cast<Companions_MovementAction>(
        (actions[0].movement % 4) + 1);
  }

  // Should have at least one movement or blocked event
  ASSERT_TRUE(move_events + blocked_events > 0);

  companions_destroy(env);
}

// =============================================================================
// Game Shell Semantics Tests
// =============================================================================
// companions_create returns the game-serving GameEnv: the world never
// terminates (no horizon done, no success done, no EpisodeEnd event). The
// plan executor's signal is companions_is_success(); is_done stays false.
// (This replaces the old TestEpisodeEnd, which verified horizon-driven done
// for the former SynchroEnv-backed create path.)
TEST(TestGameShellNeverDone) {
  Companions_EnvConfig config = MakeConfig(5, 5, 1, 1, 42);
  config.horizon = 50;
  Companions_Env* env = companions_create(&config);
  ASSERT_NOT_NULL(env);
  companions_reset(env, 42);

  Companions_Action actions[1] = {{Companions_Movement_Stay, Companions_Interact_None}};
  Companions_StepResult result = {};

  // Step well past the horizon: done must never fire (horizon only feeds the
  // steps-remaining observation feature), and the world keeps ticking.
  for (int step = 0; step < 60; step++) {
    companions_step(env, actions, 1, &result);
    ASSERT_FALSE(companions_is_done(env));
    ASSERT_FALSE(result.state.done);
  }
  ASSERT_EQ(companions_get_tick(env), 60);

  companions_destroy(env);
}

TEST(TestGameShellSuccessLatchesWithoutDone) {
  // 5x5 complexity-0 map: empty interior, single companion, single synchro
  // goal — walk the agent straight onto the goal and verify success latches
  // while done stays false (success != done for the game shell).
  Companions_EnvConfig config = MakeConfig(5, 5, 1, 1, 42);
  Companions_Env* env = companions_create(&config);
  ASSERT_NOT_NULL(env);
  companions_reset(env, 42);
  ASSERT_FALSE(companions_is_success(env));

  // Locate the synchro goal via the annotation layer (tag 0 = SynchroGoal).
  const int32_t kSynchroGoalTag = 0;
  int goal_row = -1, goal_col = -1;
  for (int r = 0; r < 5 && goal_row < 0; r++) {
    for (int c = 0; c < 5; c++) {
      if (companions_has_tag_at(env, r, c, kSynchroGoalTag)) {
        goal_row = r;
        goal_col = c;
        break;
      }
    }
  }
  ASSERT_TRUE(goal_row >= 0);

  // Manhattan-walk the agent onto the goal (no obstacles on this map).
  Companions_AgentState agent = {};
  ASSERT_TRUE(companions_get_agent_by_index(env, 0, &agent));
  int guard = 0;
  while ((agent.position.row != goal_row || agent.position.col != goal_col) &&
         guard++ < 20) {
    Companions_MovementAction mv = Companions_Movement_Stay;
    if (agent.position.row < goal_row) {
      mv = Companions_Movement_Down;
    } else if (agent.position.row > goal_row) {
      mv = Companions_Movement_Up;
    } else if (agent.position.col < goal_col) {
      mv = Companions_Movement_Right;
    } else {
      mv = Companions_Movement_Left;
    }
    Companions_Action action = {mv, Companions_Interact_None};
    Companions_StepResult result = {};
    companions_step(env, &action, 1, &result);
    ASSERT_TRUE(companions_get_agent_by_index(env, 0, &agent));
  }
  ASSERT_EQ(agent.position.row, goal_row);
  ASSERT_EQ(agent.position.col, goal_col);

  // Task success latched, but the game world is NOT done.
  ASSERT_TRUE(companions_is_success(env));
  ASSERT_FALSE(companions_is_done(env));

  // In-game executor sequence: succeed task A -> swap lens to task B -> poll
  // success for B. The lens swap must clear task A's latched success.
  ASSERT_TRUE(companions_set_task_lens(env, Companions_Lens_Dodge));
  ASSERT_FALSE(companions_is_success(env));

  // DodgeLens success requires surviving until the horizon (tick >= horizon,
  // dodge_lens.cc IsSuccess); we are only a handful of ticks into a
  // 100-tick horizon, so one Stay step cannot legitimately succeed. A stale
  // latch from task A resurfacing through companions_step would trip this.
  Companions_Action stay = {Companions_Movement_Stay, Companions_Interact_None};
  Companions_StepResult step_result = {};
  companions_step(env, &stay, 1, &step_result);
  ASSERT_FALSE(companions_is_success(env));

  companions_destroy(env);
}

TEST(TestSuccessClearedBySnapshotLoad) {
  // Snapshots capture physical state only — they do not serialize the latched
  // success flag. Loading a snapshot taken BEFORE success must therefore
  // clear any latched success, including one step later (the wrapper caches
  // success=false on load, but companions_step re-reads the latch from the
  // C++ env — a stale latch would resurface there and lie to the plan
  // executor).
  Companions_EnvConfig config = MakeConfig(5, 5, 1, 1, 42);
  Companions_Env* env = companions_create(&config);
  ASSERT_NOT_NULL(env);
  companions_reset(env, 42);
  ASSERT_FALSE(companions_is_success(env));

  // Save a snapshot of the pre-success state.
  int32_t snap_size = companions_get_snapshot_size(env);
  ASSERT_TRUE(snap_size > 0);
  std::vector<uint8_t> snapshot(snap_size);
  ASSERT_TRUE(companions_save_snapshot(env, snapshot.data(), snap_size));

  // Locate the synchro goal via the annotation layer (tag 0 = SynchroGoal).
  const int32_t kSynchroGoalTag = 0;
  int goal_row = -1, goal_col = -1;
  for (int r = 0; r < 5 && goal_row < 0; r++) {
    for (int c = 0; c < 5; c++) {
      if (companions_has_tag_at(env, r, c, kSynchroGoalTag)) {
        goal_row = r;
        goal_col = c;
        break;
      }
    }
  }
  ASSERT_TRUE(goal_row >= 0);

  // Manhattan-walk the agent onto the goal to latch success.
  Companions_AgentState agent = {};
  ASSERT_TRUE(companions_get_agent_by_index(env, 0, &agent));
  int guard = 0;
  while ((agent.position.row != goal_row || agent.position.col != goal_col) &&
         guard++ < 20) {
    Companions_MovementAction mv = Companions_Movement_Stay;
    if (agent.position.row < goal_row) {
      mv = Companions_Movement_Down;
    } else if (agent.position.row > goal_row) {
      mv = Companions_Movement_Up;
    } else if (agent.position.col < goal_col) {
      mv = Companions_Movement_Right;
    } else {
      mv = Companions_Movement_Left;
    }
    Companions_Action action = {mv, Companions_Interact_None};
    Companions_StepResult result = {};
    companions_step(env, &action, 1, &result);
    ASSERT_TRUE(companions_get_agent_by_index(env, 0, &agent));
  }
  ASSERT_TRUE(companions_is_success(env));

  // Load the pre-success snapshot: success must clear immediately...
  ASSERT_TRUE(companions_load_snapshot(env, snapshot.data(), snap_size));
  ASSERT_FALSE(companions_is_success(env));

  // ...and STAY cleared after the next step (the agent is back at its spawn,
  // off the goal — only a stale latch could report success here).
  ASSERT_TRUE(companions_get_agent_by_index(env, 0, &agent));
  ASSERT_TRUE(agent.position.row != goal_row || agent.position.col != goal_col);
  Companions_Action stay = {Companions_Movement_Stay, Companions_Interact_None};
  Companions_StepResult result = {};
  companions_step(env, &stay, 1, &result);
  ASSERT_FALSE(companions_is_success(env));

  companions_destroy(env);
}

// =============================================================================
// Episode End Event Tests (AggroEnv — the env with episode semantics)
// =============================================================================
// GameEnv never reports done, so the EpisodeEnd emission block in
// companions_step is only reachable via companions_create_aggro. This test
// restores the coverage the old TestEpisodeEnd provided before
// companions_create switched to GameEnv.
TEST(TestAggroEpisodeEndEvent) {
  Companions_AggroEnvConfig config = {};
  config.rows = 10;
  config.cols = 10;
  config.num_companions = 1;
  config.patrol_square_size = 3;
  config.horizon = 10;  // Short horizon: timeout-driven done
  config.d4_transform = 0;
  config.seed = 42;
  config.enemy_type = Companions_Enemy_Zombie;
  config.map_complexity = 0;

  Companions_Env* env = companions_create_aggro(&config);
  ASSERT_NOT_NULL(env);
  companions_reset(env, 42);

  // AggroEnv agents = companions + 1 enemy (enemy slot is FSM-driven; its
  // action is ignored but a slot must be supplied).
  const int num_agents = 2;
  std::vector<Companions_Action> actions(
      num_agents, {Companions_Movement_Stay, Companions_Interact_None});

  bool saw_done = false;
  int episode_end_events = 0;
  Companions_StepResult result = {};
  for (int step = 0; step < config.horizon + 5 && !saw_done; step++) {
    companions_step(env, actions.data(), num_agents, &result);
    if (result.state.done) {
      saw_done = true;
      for (int i = 0; i < result.event_count; i++) {
        if (result.events[i].type == Companions_Event_EpisodeEnd) {
          episode_end_events++;
          ASSERT_EQ(result.events[i].episode_steps, companions_get_tick(env));
          ASSERT_EQ(result.events[i].episode_success,
                    companions_is_success(env));
        }
      }
    } else {
      // EpisodeEnd must only fire on the done step.
      for (int i = 0; i < result.event_count; i++) {
        ASSERT_NE(result.events[i].type, Companions_Event_EpisodeEnd);
      }
    }
  }

  // Done fires at the horizon (idle agents never aggro-complete earlier),
  // with exactly one EpisodeEnd event carrying the episode stats.
  ASSERT_TRUE(saw_done);
  ASSERT_EQ(companions_get_tick(env), config.horizon);
  ASSERT_EQ(episode_end_events, 1);
  // With everyone idle the aggro task cannot succeed: timeout failure.
  ASSERT_FALSE(companions_is_success(env));

  companions_destroy(env);
}

// =============================================================================
// Special Cells Tests
// =============================================================================
TEST(TestSpecialCells) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  Companions_GameState state = {};
  companions_get_state(env, &state);

  // Should have special cells at the perimeter walls. Synchro/Target roles
  // now flow through the annotation layer rather than the physical CellKind,
  // so they're not reflected in special_cells.
  ASSERT_TRUE(state.special_cell_count > 0);

  companions_destroy(env);
}

// =============================================================================
// Action Intent vs Actual Tests
// =============================================================================
TEST(TestActionIntentVsActual) {
  // Small grid where we can predictably hit walls
  // Grid is 5x5 with walls on perimeter, agent spawns in interior
  Companions_EnvConfig config = MakeConfig(5, 5, 1, 1, 42);
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  // Get initial agent position
  Companions_AgentState agent = {};
  companions_get_agent_by_index(env, 0, &agent);

  // Walk to the top wall (row 1 is adjacent to wall at row 0)
  // Keep moving up until we hit the wall
  Companions_Action actions[1] = {{Companions_Movement_Up, Companions_Interact_None}};
  Companions_StepResult result = {};

  // Move up repeatedly until blocked
  bool found_blocked = false;
  for (int i = 0; i < 5; i++) {
    companions_step(env, actions, 1, &result);

    // Check if movement was blocked
    if (!result.state.agents[0].action_succeeded) {
      found_blocked = true;

      // CRITICAL CHECKS:
      // Intent should be Up (what we asked for)
      ASSERT_EQ(result.state.agents[0].action_intent.movement, Companions_Movement_Up);
      // Actual should be Stay (blocked by wall)
      ASSERT_EQ(result.state.agents[0].action_actual.movement, Companions_Movement_Stay);
      // action_succeeded should be false
      ASSERT_FALSE(result.state.agents[0].action_succeeded);

      break;
    } else {
      // When movement succeeds, intent should equal actual
      ASSERT_EQ(result.state.agents[0].action_intent.movement,
                result.state.agents[0].action_actual.movement);
      ASSERT_TRUE(result.state.agents[0].action_succeeded);
    }
  }

  // We should have hit the wall at some point
  ASSERT_TRUE(found_blocked);

  companions_destroy(env);
}

TEST(TestActionIntentVsActualStay) {
  // Test that Stay action has matching intent/actual
  Companions_EnvConfig config = MakeConfig(5, 5, 1, 1, 42);
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  Companions_Action actions[1] = {{Companions_Movement_Stay, Companions_Interact_None}};
  Companions_StepResult result = {};

  companions_step(env, actions, 1, &result);

  // Stay should always succeed
  ASSERT_EQ(result.state.agents[0].action_intent.movement, Companions_Movement_Stay);
  ASSERT_EQ(result.state.agents[0].action_actual.movement, Companions_Movement_Stay);
  ASSERT_TRUE(result.state.agents[0].action_succeeded);

  companions_destroy(env);
}

// =============================================================================
// Snapshot Tests
// =============================================================================

TEST(TestSnapshotSizeReturnsPositive) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  ASSERT_TRUE(env != nullptr);

  int32_t size = companions_get_snapshot_size(env);
  ASSERT_TRUE(size > 0);

  companions_destroy(env);
}

TEST(TestSaveSnapshotRoundTrip) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  ASSERT_TRUE(env != nullptr);

  // Run a few steps to change state
  Companions_Action actions[3] = {
      {Companions_Movement_Right, Companions_Interact_None},
      {Companions_Movement_Down, Companions_Interact_None},
      {Companions_Movement_Stay, Companions_Interact_None}};
  Companions_StepResult result;
  companions_step(env, actions, 3, &result);
  companions_step(env, actions, 3, &result);

  // Record state before save
  Companions_GameState state_before;
  companions_get_state(env, &state_before);

  // Save snapshot
  int32_t size = companions_get_snapshot_size(env);
  ASSERT_TRUE(size > 0);

  std::vector<uint8_t> buffer(size);
  bool save_ok = companions_save_snapshot(env, buffer.data(), size);
  ASSERT_TRUE(save_ok);

  // Reset env (changes state)
  companions_reset(env, 999);

  // Verify state changed
  Companions_GameState state_after_reset;
  companions_get_state(env, &state_after_reset);
  // Tick should be 0 after reset
  ASSERT_EQ(state_after_reset.tick, 0);

  // Load snapshot
  bool load_ok = companions_load_snapshot(env, buffer.data(), size);
  ASSERT_TRUE(load_ok);

  // Verify state restored
  Companions_GameState state_after_load;
  companions_get_state(env, &state_after_load);

  ASSERT_EQ(state_after_load.tick, state_before.tick);
  ASSERT_EQ(state_after_load.agent_count, state_before.agent_count);

  // Check agent positions match
  for (int i = 0; i < state_before.agent_count && i < Companions_MAX_AGENTS; ++i) {
    ASSERT_EQ(state_after_load.agents[i].position.row,
              state_before.agents[i].position.row);
    ASSERT_EQ(state_after_load.agents[i].position.col,
              state_before.agents[i].position.col);
  }

  companions_destroy(env);
}

TEST(TestSaveSnapshotBufferTooSmall) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  ASSERT_TRUE(env != nullptr);

  int32_t size = companions_get_snapshot_size(env);
  ASSERT_TRUE(size > 0);

  // Try to save with buffer that's too small
  std::vector<uint8_t> small_buffer(size / 2);
  bool save_ok = companions_save_snapshot(env, small_buffer.data(),
                                              static_cast<int32_t>(small_buffer.size()));
  ASSERT_FALSE(save_ok);

  // Error should be set
  const char* error = companions_get_error();
  ASSERT_TRUE(error != nullptr);
  ASSERT_TRUE(std::strlen(error) > 0);

  companions_destroy(env);
}

TEST(TestLoadSnapshotInvalidData) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  ASSERT_TRUE(env != nullptr);

  // Try to load garbage data
  uint8_t garbage[100] = {0x12, 0x34, 0x56, 0x78};  // Invalid magic
  bool load_ok = companions_load_snapshot(env, garbage, 100);
  ASSERT_FALSE(load_ok);

  // Error should be set
  const char* error = companions_get_error();
  ASSERT_TRUE(error != nullptr);
  ASSERT_TRUE(std::strlen(error) > 0);

  companions_destroy(env);
}

TEST(TestSnapshotNullArgs) {
  // Test null env
  ASSERT_EQ(companions_get_snapshot_size(nullptr), 0);

  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  ASSERT_TRUE(env != nullptr);

  // Get valid size first
  int32_t size = companions_get_snapshot_size(env);
  ASSERT_TRUE(size > 0);

  // Test null buffer
  ASSERT_FALSE(companions_save_snapshot(env, nullptr, size));

  // Test null data for load
  ASSERT_FALSE(companions_load_snapshot(env, nullptr, 100));

  // Test null env for load
  uint8_t dummy[100] = {0};
  ASSERT_FALSE(companions_load_snapshot(nullptr, dummy, 100));

  companions_destroy(env);
}

// =============================================================================
// Level Generation Tests
// =============================================================================

TEST(TestGenerateLevelBasic) {
  Companions_LevelConfig config = {};
  config.rows = 10;
  config.cols = 10;
  config.map_complexity = 0;
  config.seed = 12345;
  config.num_companions = 2;
  config.horizon = 100;

  int32_t size = companions_generate_level(&config);
  ASSERT_TRUE(size > 0);

  std::vector<uint8_t> buffer(size);
  bool ok = companions_get_generated_level(buffer.data(), size);
  ASSERT_TRUE(ok);
}

TEST(TestGenerateLevelWithSynchro) {
  Companions_LevelConfig config = {};
  config.rows = 12;
  config.cols = 12;
  config.map_complexity = 0;
  config.seed = 42;
  config.synchro_cell_count = 3;
  config.num_companions = 3;
  config.horizon = 100;

  int32_t size = companions_generate_level(&config);
  ASSERT_TRUE(size > 0);

  // Load into SynchroEnv to verify compatibility
  std::vector<uint8_t> buffer(size);
  companions_get_generated_level(buffer.data(), size);

  Companions_EnvConfig env_config = MakeConfig(12, 12, 3, 3, 999);
  Companions_Env* env = companions_create(&env_config);
  ASSERT_TRUE(env != nullptr);

  bool load_ok = companions_load_snapshot(env, buffer.data(), size);
  ASSERT_TRUE(load_ok);

  companions_destroy(env);
}

TEST(TestGenerateLevelWithPatrol) {
  Companions_LevelConfig config = {};
  config.rows = 10;
  config.cols = 10;
  config.map_complexity = 0;
  config.seed = 54321;
  config.patrol_square_size = 3;
  config.has_target_cell = true;
  config.num_companions = 1;
  config.num_enemies = 1;
  config.horizon = 100;

  int32_t size = companions_generate_level(&config);
  ASSERT_TRUE(size > 0);

  std::vector<uint8_t> buffer(size);
  bool ok = companions_get_generated_level(buffer.data(), size);
  ASSERT_TRUE(ok);
}

TEST(TestGenerateLevelNullConfig) {
  int32_t size = companions_generate_level(nullptr);
  ASSERT_EQ(size, 0);

  const char* error = companions_get_error();
  ASSERT_TRUE(error != nullptr);
  ASSERT_TRUE(std::strlen(error) > 0);
}

TEST(TestGenerateLevelInvalidDimensions) {
  Companions_LevelConfig config = {};
  config.rows = 0;  // Invalid
  config.cols = 10;
  config.seed = 42;

  int32_t size = companions_generate_level(&config);
  ASSERT_EQ(size, 0);
}

TEST(TestGetGeneratedLevelWithoutGenerate) {
  uint8_t buffer[100];
  // Clear any previously generated level by generating with invalid config
  Companions_LevelConfig bad_config = {};
  bad_config.rows = 0;
  companions_generate_level(&bad_config);

  // Now try to get without valid generation
  bool ok = companions_get_generated_level(buffer, 100);
  ASSERT_FALSE(ok);
}

// =============================================================================
// Annotation API Tests
// =============================================================================
// SemanticTag integer values (must stay in sync with annotations.h /
// htn_bridge.py SEMANTIC_TAG_NAMES).
static constexpr int32_t kTagSynchroGoal = 0;
static constexpr int32_t kTagAggroTarget = 1;
static constexpr int32_t kTagQuestPickup = 2;

TEST(TestAnnotationCountMatchesNumSynchro) {
  Companions_EnvConfig config = MakeConfig(12, 12, 3, 3, 42);
  Companions_Env* env = companions_create(&config);
  ASSERT_NOT_NULL(env);
  companions_reset(env, 42);

  // SynchroEnv places exactly `num_synchro` persistent SynchroGoal cell
  // annotations during Reset.
  int32_t count = companions_get_annotation_count(env);
  ASSERT_EQ(count, 3);

  companions_destroy(env);
}

TEST(TestAnnotationCountNullEnv) {
  ASSERT_EQ(companions_get_annotation_count(nullptr), 0);
}

TEST(TestGetAnnotationsReturnsSynchroGoals) {
  Companions_EnvConfig config = MakeConfig(12, 12, 3, 3, 42);
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  int32_t count = companions_get_annotation_count(env);
  std::vector<Companions_Annotation> anns(count);
  int32_t written = companions_get_annotations(env, anns.data(), count);
  ASSERT_EQ(written, count);

  // Every returned annotation should be a persistent cell-level SynchroGoal
  // at a valid interior position.
  for (int i = 0; i < written; i++) {
    ASSERT_EQ(anns[i].target_kind, 0);  // 0 = Cell
    ASSERT_EQ(anns[i].tag, kTagSynchroGoal);
    ASSERT_EQ(anns[i].owner_lens_id, -1);  // Persistent (external owner)
    ASSERT_TRUE(anns[i].pos.row > 0 && anns[i].pos.row < 11);
    ASSERT_TRUE(anns[i].pos.col > 0 && anns[i].pos.col < 11);
    // params_json is null-terminated
    ASSERT_EQ(anns[i].params_json[COMPANIONS_MAX_ANNOTATION_PARAMS - 1], '\0');
  }

  companions_destroy(env);
}

TEST(TestGetAnnotationsBufferTooSmall) {
  Companions_EnvConfig config = MakeConfig(12, 12, 3, 3, 42);
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  // Request fewer annotations than exist. Should write `count` and stop.
  Companions_Annotation one = {};
  int32_t written = companions_get_annotations(env, &one, 1);
  ASSERT_EQ(written, 1);
  ASSERT_EQ(one.tag, kTagSynchroGoal);

  companions_destroy(env);
}

TEST(TestGetAnnotationsNullArgs) {
  Companions_EnvConfig config = MakeConfig();
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  Companions_Annotation buf[1] = {};
  ASSERT_EQ(companions_get_annotations(nullptr, buf, 1), 0);
  ASSERT_EQ(companions_get_annotations(env, nullptr, 1), 0);
  // Zero count is a no-op (not an error).
  ASSERT_EQ(companions_get_annotations(env, buf, 0), 0);

  companions_destroy(env);
}

TEST(TestHasTagAtSynchroGoalPositions) {
  Companions_EnvConfig config = MakeConfig(12, 12, 3, 3, 42);
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  int32_t count = companions_get_annotation_count(env);
  std::vector<Companions_Annotation> anns(count);
  companions_get_annotations(env, anns.data(), count);

  // Every reported goal position answers yes; wrong tag answers no.
  for (const auto& a : anns) {
    ASSERT_TRUE(companions_has_tag_at(env, a.pos.row, a.pos.col, kTagSynchroGoal));
    ASSERT_FALSE(companions_has_tag_at(env, a.pos.row, a.pos.col, kTagAggroTarget));
    ASSERT_FALSE(companions_has_tag_at(env, a.pos.row, a.pos.col, kTagQuestPickup));
  }

  // A wall corner carries no semantic tags.
  ASSERT_FALSE(companions_has_tag_at(env, 0, 0, kTagSynchroGoal));
  // A clearly-non-goal interior position (start search from (1,1), skip goals)
  for (int r = 1; r < 11; r++) {
    for (int c = 1; c < 11; c++) {
      bool is_goal = false;
      for (const auto& a : anns) {
        if (a.pos.row == r && a.pos.col == c) { is_goal = true; break; }
      }
      if (!is_goal) {
        ASSERT_FALSE(companions_has_tag_at(env, r, c, kTagSynchroGoal));
        goto done;
      }
    }
  }
  done:;
  companions_destroy(env);
}

TEST(TestHasTagAtNullEnv) {
  ASSERT_FALSE(companions_has_tag_at(nullptr, 1, 1, kTagSynchroGoal));
}

TEST(TestAgentHasTagFalseForCompanions) {
  // SynchroEnv does not tag companions with any SemanticTag; agent-level tags
  // (TargetMob, SkillGiver, HtnName, ...) are set by the HTN planner, not the
  // default env reset.
  Companions_EnvConfig config = MakeConfig(12, 12, 3, 3, 42);
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  for (int i = 0; i < companions_get_agent_count(env); i++) {
    Companions_AgentState agent = {};
    ASSERT_TRUE(companions_get_agent_by_index(env, i, &agent));
    ASSERT_FALSE(companions_agent_has_tag(env, agent.id, kTagSynchroGoal));
    ASSERT_FALSE(companions_agent_has_tag(env, agent.id, kTagAggroTarget));
  }

  companions_destroy(env);
}

TEST(TestAgentHasTagNullEnv) {
  ASSERT_FALSE(companions_agent_has_tag(nullptr, 1, kTagSynchroGoal));
}

TEST(TestAggroEnvHasTargetAnnotation) {
  Companions_AggroEnvConfig config = {};
  config.rows = 10;
  config.cols = 10;
  config.num_companions = 1;
  config.patrol_square_size = 3;
  config.horizon = 100;
  config.d4_transform = 0;
  config.seed = 42;
  config.enemy_type = Companions_Enemy_Zombie;
  config.map_complexity = 0;

  Companions_Env* env = companions_create_aggro(&config);
  ASSERT_NOT_NULL(env);
  companions_reset(env, 42);

  // AggroEnv places exactly one persistent AggroTarget cell annotation.
  int32_t count = companions_get_annotation_count(env);
  ASSERT_TRUE(count >= 1);

  std::vector<Companions_Annotation> anns(count);
  companions_get_annotations(env, anns.data(), count);

  int target_count = 0;
  Companions_Annotation target = {};
  for (const auto& a : anns) {
    if (a.tag == kTagAggroTarget) {
      target_count++;
      target = a;
    }
  }
  ASSERT_EQ(target_count, 1);
  ASSERT_EQ(target.target_kind, 0);
  ASSERT_EQ(target.owner_lens_id, -1);
  ASSERT_TRUE(companions_has_tag_at(env, target.pos.row, target.pos.col,
                                    kTagAggroTarget));

  companions_destroy(env);
}

TEST(TestAnnotationsSurviveSnapshotRoundTrip) {
  Companions_EnvConfig config = MakeConfig(12, 12, 3, 3, 42);
  Companions_Env* env = companions_create(&config);
  companions_reset(env, 42);

  int32_t count_before = companions_get_annotation_count(env);
  std::vector<Companions_Annotation> before(count_before);
  companions_get_annotations(env, before.data(), count_before);

  // Save, reset to a different seed, reload.
  int32_t size = companions_get_snapshot_size(env);
  std::vector<uint8_t> buffer(size);
  ASSERT_TRUE(companions_save_snapshot(env, buffer.data(), size));
  companions_reset(env, 999);
  ASSERT_TRUE(companions_load_snapshot(env, buffer.data(), size));

  int32_t count_after = companions_get_annotation_count(env);
  ASSERT_EQ(count_after, count_before);

  // Every pre-save SynchroGoal position is still a SynchroGoal after reload.
  for (const auto& a : before) {
    ASSERT_TRUE(companions_has_tag_at(env, a.pos.row, a.pos.col, a.tag));
  }

  companions_destroy(env);
}

// =============================================================================
// Main
// =============================================================================
int main() {
  std::cout << "Running C API tests...\n" << std::endl;

  int passed = 0;
  int failed = 0;

  for (const auto& test : tests) {
    std::cout << "[ RUN      ] " << test.name << std::endl;
    try {
      test.func();
      std::cout << "[       OK ] " << test.name << std::endl;
      passed++;
    } catch (const std::exception& e) {
      std::cout << "[  FAILED  ] " << test.name << std::endl;
      std::cout << "  Error: " << e.what() << std::endl;
      failed++;
    }
  }

  std::cout << "\n========================================" << std::endl;
  std::cout << "Tests: " << (passed + failed) << std::endl;
  std::cout << "Passed: " << passed << std::endl;
  std::cout << "Failed: " << failed << std::endl;

  return failed > 0 ? 1 : 0;
}
